### ISSUE TITLE
Licence GPL?

### ISSUE THREAD

**Issue by guettli** [ef-ctx/tornwamp#13]
Are you sure you want to use the GPL?

Most software in the python world use BSD-like licences.

I can't use (and improve) GPL code. Sorry.

**Comment by tatiana** [comment]
Hi @guettli! If you could explain what is your problem of using a GNU GPL v2 python module, we can consider changing it. Please, just explain your POV.

**Comment by guettli** [comment]
The GPL licence is like a virus. If we would use tornwamp, which uses the GPL licence, we would need to open source our commercial software. We can't do this. That's why many projects use an Apache style licence. The main building blocks of our applications use a Apache/BSD like licence: Python, Django, PostgreSQL. You get less contributors if you use the GPL. There are few exception: linux kernel and gcc. But that's the only successful GPL project I know. That's my POV :-)

**Comment by tatiana** [comment]
I agree GNU GPL is viral, @guettli - but you can use GNU GPL without harming your business.

You can have a software application which is commercial using GNU GPL code. The only restriction is: if you distribute it, you need to provide the source code.

Considering the specific case of TornWAMP:
- would you be distributing your application to clients, installing it in their servers?

If you are only serving an app built on top of TornWAMP, you don't need to expose the source code of your application to anyone.

We're willing to change the license - if you could describe your use case :)

**Comment by guettli** [comment]
You are willing to change the licence. Nice. There is no use case. There is a policy: Don't use GPL libraries or modules. We use gcc and the linux kernel. But nothing where something like linking happens.

Please talk to other developers which have some experience in open source software. I am curious what feedback you will get.

**Comment by martianedd** [comment]
GPL is hardly an unsuccessful license. Besides Linux and GCC, there is the whole GNU project, which was started by Richard Stallman. It encompasses several projects most of which are GPL or LGPL. You have already mentioned GCC. There is also GNU emacs, glibc, among others. There is also a very successful desktop environment called gnome which is GPL. Certainly serveral people from free software community will point GPL as one of the reasons it got spread like it did.

Each license have pros and cons, of course. But by saying GPL is never good we are oversimplifying things. What I think would make a good argument for not using GPL is tell us what is it that you are mostly afraid of when you use GPL. Do you think it will make you a disservice? Why exactly? I am excited to finding out!

**Comment by guettli** [comment]
GPL is like a virus. We do closed source software development. Please search the web why Apache and Python choose a more liberal licence. Related: https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq#Which_open_source_license_should_I_use.3F

**Comment by tatiana** [comment]
Just to let you know, @guettli, the license was changed to Apache 2.0. Thanks for your feedback!

**Comment by guettli** [comment]
@tatiana thank you for changing the licence :-)
