### ISSUE TITLE
Pull request?

### ISSUE THREAD

**Issue by rexlunae** [ef-ctx/tornwamp#22]
Hi,

I considered just sending a pull request, but my changes are quite extensive and might be controversial, so I thought I would ask first to see if you have any interest in them.

I found this project, and thought it was really cool, but it didn't quite have the feature set I needed.  So, I made a fork, and started messing with it.  And, I've made some improvements/changes that might be of interest to the project.  However, I also changed quite a few things.  So, here's what I added:

1.  MessagePack serializer support using the negotiation.
2.  More complete RPC support, including the full client A -> dealer -> client B -> dealer -> client A path.
3.  uris more compliant with the WAMP protocol.
4.  Standard error messages as defined by WAMP protocol.
5.  Realm support.

In doing this, I dropped Python 2 support, because I wanted to be able to use async/await instead of the greenlets.  When I first started messing with the code base, the greenlet library didn't seem to be working.

My fork is here, if you want to have a look at it:
https://github.com/rexlunae/tornwamp

If you don't want it, I'll probably end up changing the name to avoid confusion.

Thanks.

**Comment by dmakarenko** [comment]
Hi @rexlunae,

First of all, thank you for your interest to the project.

Secondly, huge thank you for your suggestions. I've only briefly looked at your fork, but I must say it does look like a great contribution.

Lastly, I'd like to say that the current state of things with `tornwamp` is that we only maintain it without actively developing it. Therefore the best way forward would be for you to maybe rename your fork and we could put a link to in the `README.md` file.

**Comment by rexlunae** [comment]
Hi Dmitry, thanks for your response.  I think, based on what you've said,
I'm going to change the name of my project to wampnado (because I'm so
original).

Best regards,
-Eric Stith

**Comment by dmakarenko** [comment]
Thank you Eric,

We will put a link to your project in our `README.md`.
